project:
  type: website
  output-dir: _site
  resources:
    - images

website:
  title: "Dr Ian Henry – Data, Leadership & Science"
  site-url: "https://drianhenry.co.uk"
  favicon: images/favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
    right:
      - text: Tutoring
        href: https://tutoring.drianhenry.co.uk
      - text: Coaching
        href: https://coaching.drianhenry.co.uk
      - text: Consulting
        href: https://consulting.drianhenry.co.uk

format:
  html:
    theme: cosmo
    toc: false
    sitemap: true
    title-block-style: none
    page-layout: full
    css: 
      - _theme/_base.css
      - _theme/_colors.css
    include-in-header: 
      - _includes/_structured-data-main.html
      - _includes/_ga4.html
      - _includes/_favicons.html
    include-after-body: 
      - _includes/_cookie-consent.html
      - _includes/_footer.html
