project:
  type: website
  output-dir: _site

website:
  title: "Consulting – Dr Ian Henry"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Services
        href: services.qmd
      - text: Contact
        href: contact.qmd
    right:
      - text: Main Hub
        href: https://drianhenry.co.uk

format:
  html:
    theme: cosmo
    css: _theme/styles.css

